import type { UnidadConModelo } from '../types'

export const mockCatalog: UnidadConModelo[] = [
  {
    unidad_id: 'iph13p-001',
    modelo_id: 'iphone-13-pro',
    color: 'Azul Sierra',
    capacidad: '256GB',
    bateria: 87,
    condicion: 'Muy bueno',
    precio: 850000,
    descripcion_particular: 'Rasguño leve en el marco lateral izquierdo, pantalla perfecta.',
    disponible: true,
    imagen_url: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-blue-select?wid=940&hei=1112&fmt=png-alpha',
    modelo: {
      modelo_id: 'iphone-13-pro',
      tipo: 'iPhone',
      nombre: 'iPhone 13 Pro',
      descripcion_general: 'El iPhone 13 Pro lleva la experiencia Pro a un nuevo nivel con un sistema de cámara Pro de triple lente, chip A15 Bionic y pantalla Super Retina XDR con ProMotion.',
      specs: 'Chip A15 Bionic · Pantalla 6.1" Super Retina XDR ProMotion · Triple cámara 12MP · 5G · Face ID · iOS 17',
      imagen_principal: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-blue-select?wid=940&hei=1112&fmt=png-alpha',
    },
  },
  {
    unidad_id: 'iph14-001',
    modelo_id: 'iphone-14',
    color: 'Medianoche',
    capacidad: '128GB',
    bateria: 91,
    condicion: 'Excelente',
    precio: 720000,
    descripcion_particular: 'Sin marcas, como nuevo. Cargador incluido.',
    disponible: true,
    imagen_url: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-midnight-select?wid=940&hei=1112&fmt=png-alpha',
    modelo: {
      modelo_id: 'iphone-14',
      tipo: 'iPhone',
      nombre: 'iPhone 14',
      descripcion_general: 'El iPhone 14 ofrece el chip A15 Bionic, modo de acción y modo cinematográfico para videos de nivel profesional.',
      specs: 'Chip A15 Bionic · Pantalla 6.1" Super Retina XDR · Cámara 12MP · 5G · Face ID · iOS 17',
      imagen_principal: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-midnight-select?wid=940&hei=1112&fmt=png-alpha',
    },
  },
  {
    unidad_id: 'iph15pm-001',
    modelo_id: 'iphone-15-pro-max',
    color: 'Titanio Natural',
    capacidad: '512GB',
    bateria: 95,
    condicion: 'Excelente',
    precio: 1450000,
    descripcion_particular: 'Impecable. Comprado hace 4 meses. Con funda y vidrio templado.',
    disponible: true,
    imagen_url: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-naturaltitanium-select?wid=940&hei=1112&fmt=png-alpha',
    modelo: {
      modelo_id: 'iphone-15-pro-max',
      tipo: 'iPhone',
      nombre: 'iPhone 15 Pro Max',
      descripcion_general: 'El iPhone 15 Pro Max presenta titanio de grado aeroespacial, chip A17 Pro y el botón de acción personalizable.',
      specs: 'Chip A17 Pro · Pantalla 6.7" Super Retina XDR ProMotion · Cámara 48MP · 5G · Face ID · USB-C',
      imagen_principal: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-naturaltitanium-select?wid=940&hei=1112&fmt=png-alpha',
    },
  },
  {
    unidad_id: 'mbam2-001',
    modelo_id: 'macbook-air-m2',
    color: 'Plata',
    capacidad: '256GB SSD · 8GB RAM',
    bateria: 92,
    condicion: 'Muy bueno',
    precio: 1200000,
    descripcion_particular: 'Pequeña marca en la tapa exterior, no afecta el uso. Batería en perfecto estado.',
    disponible: true,
    imagen_url: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=904&hei=840&fmt=jpeg',
    modelo: {
      modelo_id: 'macbook-air-m2',
      tipo: 'Mac',
      nombre: 'MacBook Air M2',
      descripcion_general: 'El MacBook Air con chip M2 es increíblemente fino y potente, con hasta 18 horas de batería y pantalla Liquid Retina de 13.6".',
      specs: 'Chip M2 · Pantalla 13.6" Liquid Retina · GPU 8 núcleos · Wi-Fi 6 · MagSafe · macOS',
      imagen_principal: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=904&hei=840&fmt=jpeg',
    },
  },
  {
    unidad_id: 'mbpm3-001',
    modelo_id: 'macbook-pro-m3',
    color: 'Gris Espacial',
    capacidad: '512GB SSD · 16GB RAM',
    bateria: 88,
    condicion: 'Excelente',
    precio: 2100000,
    descripcion_particular: 'Sin marcas. Año 2024. Incluye cargador 96W.',
    disponible: true,
    imagen_url: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-spacegray-select-202310?wid=904&hei=840&fmt=jpeg',
    modelo: {
      modelo_id: 'macbook-pro-m3',
      tipo: 'Mac',
      nombre: 'MacBook Pro M3',
      descripcion_general: 'El MacBook Pro con chip M3 ofrece rendimiento profesional con pantalla Liquid Retina XDR y hasta 22 horas de batería.',
      specs: 'Chip M3 · Pantalla 14.2" Liquid Retina XDR · GPU 10 núcleos · Wi-Fi 6E · HDMI · SD Card',
      imagen_principal: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-spacegray-select-202310?wid=904&hei=840&fmt=jpeg',
    },
  },
  {
    unidad_id: 'iph12-001',
    modelo_id: 'iphone-12',
    color: 'Rojo',
    capacidad: '64GB',
    bateria: 78,
    condicion: 'Bueno',
    precio: 480000,
    descripcion_particular: 'Rayones menores en la pantalla visibles con luz directa. Funciona perfecto.',
    disponible: true,
    imagen_url: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select?wid=940&hei=1112&fmt=png-alpha',
    modelo: {
      modelo_id: 'iphone-12',
      tipo: 'iPhone',
      nombre: 'iPhone 12',
      descripcion_general: 'El iPhone 12 presenta diseño plano con Ceramic Shield, chip A14 Bionic y compatibilidad con 5G.',
      specs: 'Chip A14 Bionic · Pantalla 6.1" Super Retina XDR · Cámara 12MP · 5G · Face ID · MagSafe',
      imagen_principal: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select?wid=940&hei=1112&fmt=png-alpha',
    },
  },
]
